name: icecite
description: The Icecite Research paper Management System.
dependencies:
  polymer: ^0.16.3
  animation: any 
  crypto: any
  uuid: any
  barback: any
# google_oauth2_client: any TODO: Use this dependency again. Currently there is a bug with firefox.
  intl: any
transformers:
- polymer:
    entry_points: 
    - web/icecite.html