name: icecite
description: The Icecite Research paper Management System.
dependencies:
#    polymer: 0.11.0+5
    polymer: ">=0.12.0 <0.13.0"
    animation: any 
    crypto: any
    uuid: any
    barback: any
    google_oauth2_client: any
    intl: any
    logging: any
transformers:
- icecite/merge_properties_transformer
- polymer:
    entry_points: web/icecite.html