name: icecite
description: A sample Polymer application
dependencies:
    polymer: any
    observe: any
    animation: any 
    crypto: any
    quiver: any
#   google_oauth2_client: any TODO: Use this dependency again. Currently there is a bug with firefox.
    intl: any
transformers:
- polymer:
    entry_points: web/icecite.html